package Day3;

import java.util.Map;

final class Priorities {

    static final Map<Character, Integer> PRIORITIES = Map.ofEntries(
            Map.entry('a', 1),
            Map.entry('b', 2),
            Map.entry('c', 3),
            Map.entry('d', 4),
            Map.entry('e', 5),
            Map.entry('f', 6),
            Map.entry('g', 7),
            Map.entry('h', 8),
            Map.entry('i', 9),
            Map.entry('j', 10),
            Map.entry('k', 11),
            Map.entry('l', 12),
            Map.entry('m', 13),
            Map.entry('n', 14),
            Map.entry('o', 15),
            Map.entry('p', 16),
            Map.entry('q', 17),
            Map.entry('r', 18),
            Map.entry('s', 19),
            Map.entry('t', 20),
            Map.entry('u', 21),
            Map.entry('v', 22),
            Map.entry('w', 23),
            Map.entry('x', 24),
            Map.entry('y', 25),
            Map.entry('z', 26),
            Map.entry('A', 27),
            Map.entry('B', 28),
            Map.entry('C', 29),
            Map.entry('D', 30),
            Map.entry('E', 31),
            Map.entry('F', 32),
            Map.entry('G', 33),
            Map.entry('H', 34),
            Map.entry('I', 35),
            Map.entry('J', 36),
            Map.entry('K', 37),
            Map.entry('L', 38),
            Map.entry('M', 39),
            Map.entry('N', 40),
            Map.entry('O', 41),
            Map.entry('P', 42),
            Map.entry('Q', 43),
            Map.entry('R', 44),
            Map.entry('S', 45),
            Map.entry('T', 46),
            Map.entry('U', 47),
            Map.entry('V', 48),
            Map.entry('W', 49),
            Map.entry('X', 50),
            Map.entry('Y', 51),
            Map.entry('Z', 52)
    );

}
